name: Full API & UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ------------------- Install and Run Backend -------------------
      - name: Install and Start Backend
        run: |
          cd mern-crud-auth-master
          npm install
          npm run dev

      # ------------------- Install and Run Frontend -------------------
      - name: Install and Start Frontend
        run: |
          cd mern-crud-auth-master/client
          npm install
          npm run dev

      # ------------------- Setup Python for Tests -------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies + Playwright
        working-directory: qa-tests
        run: |
          pip install -r requirements.txt
          pip install playwright
          playwright install  # Install browser binaries

      # ------------------- Run UI Tests -------------------
      - name: Run UI Tests
        working-directory: qa-tests/tests/UI
        run: xvfb-run pytest


      # ------------------- Run API Tests -------------------
      - name: Run API Tests
        working-directory: qa-tests/tests/API
        run: pytest