name: Run UI and API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install backend dependencies and start server
      - name: Setup Backend
        working-directory: backend
        run: |
          npm install
          nohup npm start &

      # Install frontend (client) dependencies and start Vite in headless
      - name: Setup Frontend
        working-directory: client
        run: |
          npm install
          nohup npm run dev -- --host &

      # Wait for frontend and backend to be up (adjust the delay if needed)
      - name: Wait for servers
        run: sleep 10

      # Setup Python & dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r qa-tests/requirements.txt

      # Run API tests (optional)
      - name: Run API Tests
        working-directory: qa-tests/tests/API
        run: pytest

      # Run UI tests in headless mode
      - name: Run UI Tests
        working-directory: qa-tests/tests/UI
        run: |
          pytest --headed=false
