name: Run UI + API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ------------------- Run UI Tests -------------------
      - name: Run UI Tests (headless)
        working-directory: qa-tests/tests/UI
        continue-on-error: true  # ❗ Prevents job from failing even if UI tests fail
        run: |
          pytest --browser=chromium

      # ------------------- Run API Tests -------------------
      - name: Run API Tests
        working-directory: qa-tests/tests/API
        run: |
          pytest
